"""Initial

Revision ID: d398ecc4b176
Revises: 
Create Date: 2022-03-10 12:05:27.792062

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d398ecc4b176"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "room",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=36), nullable=False),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("room")
    # ### end Alembic commands ###
